### PR TITLE
Optimize MadelineSilhouetteTrigger code's compatibility

### PR DESCRIPTION
**Pull request by AAA1459**
made player must become silhouette when it should, not will be interrupted by other mod

### CODE REVIEW

**Comment by microlith57** [comment]
i'm not sure why this is necessary; surely you can just check `player.Sprite.Mode == PlayerSpriteMode.Playback`? that uses only vanilla public fields, and achieves basically the same result (unless you need to check _specifically_ for maddyhelpinghand's silhouette mode?)

**Comment by AAA1459** [comment]
> i'm not sure why this is necessary; surely you can just check `player.Sprite.Mode == PlayerSpriteMode.Playback`? that uses only vanilla public fields, and achieves basically the same result (unless you need to check _specifically_ for maddyhelpinghand's silhouette mode?)

i don't understand what you're curious about.  although about the end, i do need that "check specifically"

**Comment by microlith57** [comment]
i'm curious as to what you're doing such that you need to check this field without using an assembly reference or checking the sprite mode

**Comment by AAA1459** [comment]
> i'm curious as to what you're doing such that you need to check this field without using an assembly reference or checking the sprite mode

Because i don't want to add many assembly references. I'm lazy

**Comment by maddie480** [comment]
(That cryptic dos2unix commit of mine https://github.com/maddie480/MaddieHelpingHand/pull/16/commits/7d2a144cccb42a403048bcea8059db3080630649 is me turning Windows line endings to Unix ones to get a diff that actually makes sense)

Why do you need to distinguish helping hand silhouette from "regular" silhouette, since if you don't want to override Madeline silhouettes, you're going to also encounter the same issue with player playbacks (like in Farewell)?

If you want to hook the PlayerSprite constructor, you can wrap the hooking with a DetourContext to specify the hooking order and decide whether you or Helping Hand goes first:

```cs
using (new DetourContext() { Before = { "*" } }) {
    IL.Celeste.Player.Render += patchPlayerRender;
}
```

**Comment by AAA1459** [comment]
> (That cryptic dos2unix commit of mine [7d2a144](https://github.com/maddie480/MaddieHelpingHand/commit/7d2a144cccb42a403048bcea8059db3080630649) is me turning Windows line endings to Unix ones to get a diff that actually makes sense)
> 
> Why do you need to distinguish helping hand silhouette from "regular" silhouette, since if you don't want to override Madeline silhouettes, you're going to also encounter the same issue with player playbacks (like in Farewell)?
> 
> If you want to hook the PlayerSprite constructor, you can wrap the hooking with a DetourContext to specify the hooking order and decide whether you or Helping Hand goes first:
> 
> ```cs
> using (new DetourContext() { Before = { "*" } }) {
>     IL.Celeste.Player.Render += patchPlayerRender;
> }
> ```

I mainly hope that other mods can ignore any of these things, no need any more way, 
and my main goal only is "made Helping Hand's silhouette not will be interrupted by natural sorting wtih other mod".

**Comment by maddie480** [comment]
still not sure why the silhouette needs to be enforced like that (on every frame), it sounds like it would fight with other mods that _want_ to replace the silhouette 🤔 and the DynData call on every frame might be a bit bad for performance

**Comment by AAA1459** [comment]
> still not sure why the silhouette needs to be enforced like that (on every frame), it sounds like it would fight with other mods that _want_ to replace the silhouette 🤔 and the DynData call on every frame might be a bit bad for performance

For Mods that both Silhouette and (or only)Madeline want to replace, 
It prevents Madeline's mode value from turning into a non-vanilla value first, that can't get silhouette

**Pull request closed without merging**
